CAMINHO_DATASET = '../dados/datasets/'
CAMINHO_SOLUCAO = '../resultados/solucoes/' 
CAMINHO_VISUALIZACAO = '../resultados/visualizacoes/'
CAMINHO_MELHOR_SOLUCAO = '../dados/melhores_solucoes/'
CAMINHO_TABELA = '../resultados/' 

EXTENSAO_DATASET = '.vrp'
EXTENSAO_SOLUCAO = '.sol'
EXTENSAO_MATRIZ_DIST = '.dist'
EXTENSAO_TABULCAO_DADOS = '.csv'

PROPORCAO_PONTO = 7
TXT_PESO = '-peso'
TXT_SOLUCAO = '-solucao'
TAM_FONTE_LEGENDA = 7
TAMANHO_PONTO = 40
TAMANHO_ROTULO = 5
TAMANHO_LINHA_ROTA = 0.7
TAMANHO_BORDA_PONTO = 0.1
POSICAO_ROTULO = 0.8
LIMITE_PLOT_CAMINHO_DEPOSITO = 20
DPI = 300
