CAMINHO_DATASET = '../dados/datasets/'
CAMINHO_SOLUCAO = '../resultados/solucoes/' 
CAMINHO_VISUALIZACAO = '../resultados/visualizacoes/'

EXTENSAO_DATASET = '.vrp'
EXTENSAO_SOLUCAO = '.sol'
EXTENSAO_MATRIZ_DIST = '.dist'

PROPORCAO_PONTO = 5
TXT_PESO = '-peso'
TAM_FONTE_LEGENDA = 7
TAMANHO_PONTO = 15
TAMANHO_ROTULO = 5
POSICAO_ROTULO = 0.7
DPI = 300
